image: fenicsproject/stable-src
script:
  - sudo apt-get update
  - sudo apt-get -y install python-six
  - git clone https://git@bitbucket.org/fenics-project/ffc
  - cd ffc
  - sudo python setup.py install --prefix=/home/fenics
  - cd ..
  - git clone https://git@bitbucket.org/fenics-project/fiat
  - cd fiat
  - sudo python setup.py install --prefix=/home/fenics
  - cd ..
  - git clone https://git@bitbucket.org/fenics-project/instant
  - cd instant
  - sudo python setup.py install --prefix=/home/fenics
  - cd ..
  - git clone https://git@bitbucket.org/fenics-project/ufl
  - cd ufl
  - sudo python setup.py install --prefix=/home/fenics
  - cd ..
  - export PATH=$PATH:/home/fenics/bin
  - export PYTHONPATH=$PYTHONPATH:/home/fenics/lib/python2.7/site-packages
  - export UFC_DIR=/home/fenics
  - ./cmake.drone
notify:
  email:
    recipients:
      - chris@bpi.cam.ac.uk

