image: gcc4.8
script:
  - sudo apt-get -y install libboost1.48-all-dev libeigen3-dev python-numpy python-six python-scientific python-ply libptscotch-dev swig
  - git clone https://git@bigbucket.org/fenics-project/ffc
  - cd ffc
  - sudo python setup.py install
  - cd ..
  - git clone https://git@bigbucket.org/fenics-project/fiat
  - cd fiat
  - sudo python setup.py install
  - cd ..
  - git clone https://git@bigbucket.org/fenics-project/instant
  - cd instant
  - sudo python setup.py install
  - cd ..
  - git clone https://git@bigbucket.org/fenics-project/ufl
  - cd ufl
  - sudo python setup.py install
  - cd ..
  - ./cmake.local
notify:
  email:
    recipients:
      - chris@bpi.cam.ac.uk

