image: fenicsproject/stable-src
cache:
  - /tmp/ccache
script:
  - whoami
  - sudo apt-get update
  - sudo apt-get -y install ccache python-six
  - export PATH=/usr/lib/ccache:/home/fenics/bin:$PATH
  - export CCACHE_DIR=/tmp/ccache
  - mkdir -p $CCACHE_DIR
  - git clone https://git@bitbucket.org/fenics-project/ffc
  - cd ffc
  - sudo python setup.py install --prefix=/home/fenics > /dev/null
  - cd ..
  - git clone https://git@bitbucket.org/fenics-project/fiat
  - cd fiat
  - sudo python setup.py install --prefix=/home/fenics > /dev/null
  - cd ..
  - git clone https://git@bitbucket.org/fenics-project/instant
  - cd instant
  - sudo python setup.py install --prefix=/home/fenics > /dev/null
  - cd ..
  - git clone https://git@bitbucket.org/fenics-project/ufl
  - cd ufl
  - sudo python setup.py install --prefix=/home/fenics > /dev/null
  - cd ..
  - export PYTHONPATH=$PYTHONPATH:/home/fenics/lib/python2.7/site-packages
  - export UFC_DIR=/home/fenics
  - ./cmake.drone
notify:
  email:
    recipients:
      - chris@bpi.cam.ac.uk

