image: quay.io/fenicsproject/dev-env:latest

pipelines:
  default:
    - step:
        script:
          - pip2 install git+https://bitbucket.org/fenics-project/fiat.git@master
          - pip2 install git+https://bitbucket.org/fenics-project/ufl.git@master
          - pip2 install git+https://bitbucket.org/fenics-project/dijitso.git@master
          - pip2 install git+https://bitbucket.org/fenics-project/instant.git@master
          - pip2 install git+https://bitbucket.org/fenics-project/ffc.git@master
          - mkdir -p build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=Debug
          - make
          - make install
          - make run_quicktest
