image: quay.io/fenicsproject/dev-env:latest

# Note: Our pipelines image does not work for DOLFIN because it's missing
# Boost, Eigen and possibly other packages.
#image: quay.io/fenicsproject/pipelines

pipelines:
  default:
    - step:
        script:
          - pip3 install git+https://bitbucket.org/fenics-project/fiat.git@master
          - pip3 install git+https://bitbucket.org/fenics-project/ufl.git@master
          - pip3 install git+https://bitbucket.org/fenics-project/dijitso.git@master
          - pip3 install git+https://bitbucket.org/fenics-project/instant.git@master
          - pip3 install git+https://bitbucket.org/fenics-project/ffc.git@master
          - mkdir -p build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=Debug -DDOLFIN_ENABLE_TESTING=ON
          - make
          - make install
          - source /usr/local/share/dolfin/dolfin.conf
          - make run_quicktest
branches:
  next:
      - step:
        script:
          - pip3 install git+https://bitbucket.org/fenics-project/fiat.git@next
          - pip3 install git+https://bitbucket.org/fenics-project/ufl.git@next
          - pip3 install git+https://bitbucket.org/fenics-project/dijitso.git@next
          - pip3 install git+https://bitbucket.org/fenics-project/instant.git@next
          - pip3 install git+https://bitbucket.org/fenics-project/ffc.git@next
          - mkdir -p build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=Debug -DDOLFIN_ENABLE_TESTING=ON
          - make
          - make install
          - source /usr/local/share/dolfin/dolfin.conf
          - make run_quicktest
