version: 2
jobs:
  build:
    docker:
      - image: quay.io/fenicsproject/dev-env:latest
    working_directory: /home/fenics/working
    steps:
      - run:
          name: Clone DOLFIN
          command: git lfs clone https://bitbucket.org/"${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}".git .
      - checkout
      - run:
          name: Install/update dependencies  # Install with sudo as tests not run as superuser in circleci/python
          command: |
            sudo pip3 install pytest six --upgrade
      - run:
          name: Install FIAT
          command: pip3 install git+https://bitbucket.org/fenics-project/fiat.git@master
      - run:
          name: Install UFL
          command: pip3 install git+https://bitbucket.org/fenics-project/ufl.git@master
      - run:
          name: Install Dijitso
          command: pip3 install git+https://bitbucket.org/fenics-project/dijitso.git@master
      - run:
          name: Install Instant
          command: pip3 install git+https://bitbucket.org/fenics-project/instant.git@master
      - run:
          name: Install FFC
          command: pip3 install git+https://bitbucket.org/fenics-project/ffc.git@master
      - run:
          name: Configure DOLFIN
          command: mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug -DDOLFIN_ENABLE_TESTING=ON
      - run:
          name: Build DOLFIN and install
          command: cd build && make install
      - run:
          name: Run Python unit tests (serial)
          command: source /usr/local/share/dolfin/dolfin.conf && python3 -m pytest test/unit/python/
      - run:
          name: Run Python unit tests (MPI)
          command: source /usr/local/share/dolfin/dolfin.conf && mpirun -n 3 python3 -m pytest test/unit/python/
      - run:
          name: Run C++ unit tests
          command: source /usr/local/share/dolfin/dolfin.conf && cd build && make run_unittests_cpp
      - run:
          name: Run Python regressions tests (serial)
          command: source /usr/local/share/dolfin/dolfin.conf && cd build && make run_regressiontests_py
      - run:
          name: Run Python regressions tests (MPI)
          command: source /usr/local/share/dolfin/dolfin.conf && cd build && make run_regressiontests_py_mpi
      - run:
          name: Run C++ regressions tests (serial)
          command: source /usr/local/share/dolfin/dolfin.conf && cd build && make run_regressiontests_cpp
      - run:
          name: Run C++ regression tests (MPI)
          command: source /usr/local/share/dolfin/dolfin.conf && cd build && make run_regressiontests_cpp_mpi
