version: 2
jobs:
  build:
    docker:
      - image: quay.io/fenicsproject/dev-env:latest
    working_directory: /home/fenics/working
    steps:
      #- run:
      #    name: Add Bitbucket key
      #    command: |
      #      mkdir -p ~/.ssh
      #      ssh-keyscan -H bitbucket.org >> ~/.ssh/known_hosts
      #      #ssh git@github.com git-lfs-authenticate "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" download
      - run:
          name: Clone DOLFIN
          command: echo $PWD echo $&& git clone https://bitbucket.org/"${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}".git .
          #command: echo $PWD && git clone https://bitbucket.org/fenics-project/dolfin.git .
      - checkout
      - run:
          name: Install FIAT
          command: pip3 install git+https://bitbucket.org/fenics-project/fiat.git@master
      - run:
          name: Install UFL
          command: pip3 install git+https://bitbucket.org/fenics-project/ufl.git@master
      - run:
          name: Install Dijitso
          command: pip3 install git+https://bitbucket.org/fenics-project/dijitso.git@master
      - run:
          name: Install Instant
          command: pip3 install git+https://bitbucket.org/fenics-project/instant.git@master
      - run:
          name: Install FFC
          command: pip3 install git+https://bitbucket.org/fenics-project/ffc.git@master

      - run:
          name: Configure DOLFIN
          command: mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug -DDOLFIN_ENABLE_TESTING=ON
      - run:
          name: Build
          command: cd build && make install
      - run:
          name: Run Python unit tests
          command: source /usr/local/share/dolfin/dolfin.conf && cd test/unit/python && python3 -m pytest .
